spring:
  profiles: # profiles 설정
    active: dev # 다른 설정이 없을 때 default 환경 값
  # jpa설정
  jpa:
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true # 보여지는 쿼리를 예쁘게 포맷팅 -> 사용하지않으면 긴 줄 형태로 출력됌

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

server:
  port: 8081

  # redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000 # 서버와의 연결 시도 및 응답 대기 시간 최대 5초

# 로그 레벨 설정
logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web.socket: trace

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.ssafy.airlingo
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

#s3
cloud:
  aws:
    s3:
      bucket: airlingobucket
    credentials:
      accessKey: AKIA456JDTAY624ZQAE7
      secretKey: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false