spring:
  profiles: # profiles 설정
    active: dev # 다른 설정이 없을 때 default 환경 값

server:
  port: 8082

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.ssafy.airlingo
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true